### ISSUE TITLE
Error after update to 4.0.10

### ISSUE THREAD

**Issue by widewebpro** [FosterCommerce/klaviyoconnect#87]
I am getting an error when using the plugin:

**Return value of fostercommerce\klaviyoconnect\services\Base::getSetting() must be an instance of fostercommerce\klaviyoconnect\services\mixed, string returned**

**Comment by fantasticmachine** [comment]
Hi @widewebpro
We will look into this asap. I think it should be a very simple fix. Apologies for the inconvenience.

**Comment by widewebpro** [comment]
@fantasticmachine All ok. Thanks!

**Comment by fantasticmachine** [comment]
@widewebpro They didn't disable the Identify API but only removed a "feature" of it where you could update the email, telephone or ID using the Identify API. 

Release 4.1.0 added some features to the plugin which would allow you to update the email or telephone number via a new controller should you wish to.

**Comment by fantasticmachine** [comment]
@widewebpro can you tell me how/where you encountered this error message? I'm not able to reproduce it.
If there was a stack trace, could you post it here please?

**Comment by fantasticmachine** [comment]
@widewebpro I'm unable to reproduce this issue.

Can you tell me which version of Craft you are using and the exact circumstances where you encountered the error?

**Comment by steve-holland** [comment]
Hey @fantasticmachine I'm also having the same issue. I think it might be because you've used 'mixed' as the return type which is for PHP8 and above. I'm only on 7.4 at the minute.

**Comment by widewebpro** [comment]
@fantasticmachine 

PHP version | 7.4.28
-- | --
Linux 5.11.0-1022-aws
MySQL 8.0.23
Imagick 3.6.0 (ImageMagick 6.9.10-23)
Craft Pro 3.7.24
2.0.45
v2.14.13
7.4.5

**Comment by fantasticmachine** [comment]
Ah, thanks @steve-holland 

@widewebpro I'll get that updated shortly

**Comment by fantasticmachine** [comment]
@widewebpro @steve-holland 
Have just published a release for 4.0.11 which should fix this issue. This release is on the develop-craft3 branch. 

Going forward, the Craft 3 version will be on this branch, with the Craft 4 (and future versions) being on Master. 
It's getting a little difficult to manage changes across the 2 versions from the same repo so do let me know if there is an issue installing. We may have to set up the branches differently.

**Comment by widewebpro** [comment]
@fantasticmachine I updated but I get a different error, when entering the settings page:

**Return value of fostercommerce\klaviyoconnect\services\Base::getSetting() must be an instance of fostercommerce\klaviyoconnect\services\mixed, string returned**

**Comment by steve-holland** [comment]
@fantasticmachine I think you're going to have to add some versions to the composer file, to mark the Craft 4 version to specifically require PHP 8 and Craft 4. At the minute, Craft is showing all the versions on the upgrade page, so upgrading will give us PHP 7.4 folks the same issues. See here:

https://craftcms.com/docs/4.x/extend/updating-plugins.html#plugin-store-considerations

**Comment by fantasticmachine** [comment]
@widewebpro @steve-holland 
Apologies once again. 
The plugin store should be showing 4.0.x for Craft 3 and 5.0.x for Craft 4. Regardless, I'll get a test environment set up locally with 7.4 to check over this again.

**Comment by steve-holland** [comment]
@fantasticmachine It's still showing 4.0.11, 5.0.0 & 5.0.1 for me I'm afraid.

PHP - 7.4.21
OS - Darwin 21.5.0
MySQL - 5.7.34
Craft Pro - 3.7.46

**Comment by fantasticmachine** [comment]
@steve-holland are you saying it's installing 5.0.x on Craft 3? It shouldn't do that as there is a version constraint for Craft.

Can you try requiring the specific version (4.0.11) ?

**Comment by widewebpro** [comment]
@fantasticmachine 

I get error, when entering the settings page:

**Return value of fostercommerce\klaviyoconnect\services\Base::getSetting() must be an instance of fostercommerce\klaviyoconnect\services\mixed, string returned**

I think the problem is mixed type. It is available with PHP 8. And for Craft CMS 3.7, PHP 7.4 is used. If I manually change the type of the returned value to a string in the vendor, then this error disappears and a new one appears with the mixed type.

**Return value of fostercommerce\klaviyoconnect\variables\Variable::lists() must be an instance of fostercommerce\klaviyoconnect\variables\mixed, null returned**

<img width="311" alt="image" src="https://user-images.githubusercontent.com/66615356/176608506-9f9ba75d-c4ae-411b-82ce-eac7ddb5eaa7.png">


<img width="433" alt="image" src="https://user-images.githubusercontent.com/66615356/176608011-857d16f6-ce0a-4356-bab7-5a66e5e4168c.png">


<img width="263" alt="image" src="https://user-images.githubusercontent.com/66615356/176607013-e577631b-3b67-4c81-a686-32d569051991.png">

**Comment by sajjanstha** [comment]
@fantasticmachine I am on Craft 3 and it's still showing 5.0.1 available when I run 
`php craft update`

**Comment by steve-holland** [comment]
@fantasticmachine I think there must be some step missing. I would expect if I was on Craft 3 with PHP 7, that the only update I would see is to v4.0.11. Currently I'm shown all 3 updates, two of which will definitely break.
 
<img width="488" alt="Screenshot 2022-06-30 at 09 06 15" src="https://user-images.githubusercontent.com/374926/176626484-5a566a3b-7889-4857-9a21-e13d342b8838.png">


<img width="1115" alt="Screenshot 2022-06-30 at 09 09 00" src="https://user-images.githubusercontent.com/374926/176626652-0e075ead-c57d-4e20-a21c-4d73acb981bf.png">

Maybe there's some extra step that needs to be done with the plugin store or something like that?

**Comment by steve-holland** [comment]
Actually @fantasticmachine are you sure you've put the php and craft constraints in the two v5 releases? Only if I'm looking in the right place, I can only see them in the v4.0.11, not 5.0.0 or 5.0.1. Maybe that's it?

**Comment by fantasticmachine** [comment]
I'll take another look at this today. Something, somewhere has got messed up.
You should only see 4.0.11 for Craft 3 and 5.0.1 for Craft 4

**Comment by fantasticmachine** [comment]
I'm having trouble resolving this issue right now.
If you're on Craft 3 then you can get the correct version by changing your composer requirement to 

`"fostercommerce/klaviyoconnect": "dev-develop-craft3"`

**Comment by steve-holland** [comment]
@fantasticmachine Good news, I can now only see 4.0.11 release in the control panel updates and via the command line. 👍🏻

**Comment by fantasticmachine** [comment]
🎉

**Comment by fantasticmachine** [comment]
@widewebpro @sajjanstha Can you let me know if this is now working OK for you?

**Comment by widewebpro** [comment]
@fantasticmachine Hey. It looks like the problems with the `mixed` type that I encountered are resolved in the `develop-craft3` branch, can you update version 4.0.11 with these bugs fixed or will you support it for PHP 8?

**Comment by fantasticmachine** [comment]
@widewebpro That's good to know. The real issue is that the tags/releases were messed up. Would you mind trying to install from the main branch again and confirm which version it tries to install?

**Comment by widewebpro** [comment]
@fantasticmachine If I installed via plugin store, I get "5.0.1" version with PHP 7.4 in config.

**Comment by sajjanstha** [comment]
@fantasticmachine It now shows 4.0.11 available for craft 3 but I am facing some problem while trying to update. I have create a new issue [here](https://github.com/FosterCommerce/klaviyoconnect/issues/89)

**Comment by steve-holland** [comment]
Hi @widewebpro I'm not actually a maintainer of this plugin, just a user like you. So I'm afraid you'll have to wait for a response from @fantasticmachine. I've not actually had a chance to try the update yet myself after the version issues.

**Comment by sajjanstha** [comment]
@widewebpro I am facing the same issue and I have created a new issue [here](https://github.com/FosterCommerce/klaviyoconnect/issues/90)

**Comment by widewebpro** [comment]
@steve-holland oh, sorry
